MTGToolbox.Web/Models/ErrorViewModel.cs
using System;

namespace MTGToolbox.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MTGToolbox.Web/Controllers/CardController.cs
using Microsoft.AspNetCore.Mvc;
using MTGToolbox.Abstract;

namespace MTGToolbox.Web.Controllers
{
    public class CardController : Controller
    {
        private readonly ICardRepository _cardRepository;

        public CardController(ICardRepository card)
        {
            _cardRepository = card;
        }

        public IActionResult GridList()
        {
            var cards = _cardRepository.GetCards();

            return View(cards);
        }
    }
}

MTGToolbox.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MTGToolbox.Web.Models;

namespace MTGToolbox.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MTGToolbox.Web/Views/Card/GridList.cshtml
@model IEnumerable<MTGToolbox.Abstract.ICard>

@{
    ViewData["Title"] = "GridList";
}

<h2>Cards</h2>

<div class="flex-grid">
    @foreach (var item in Model)
    {
        <div>
            <img class="img-thumbnail" src="@Url.Content(@item.ImageFile)" />
        </div>
    }
</div>

MTGToolbox.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MTGToolbox</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar-default">
            <ul class="nav navbar-nav">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        Home
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("GridList", "Card")">
                        Cards
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MTGToolbox</p>
        </footer>
    </div>
</body>
</html>